### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by ajdapretnar**
Just a few fixes for the website.

I still cannot figure out why hugo puts a space after link. It is so annoying, when you have a full stop at the end and don't wish to include it in the link.

### CODE REVIEW

**Comment by matjazp** [comment]
Some pointers for extra space problem: https://gohugo.io/templates/introduction/#whitespace
and https://discourse.gohugo.io/t/solved-extra-space-after-shortcode-output/6736

**Comment by ajdapretnar** [comment]
@matjazp Doesn't seem to work for links...

**Comment by matjazp** [comment]
I'll fix it. Shortcode for link_new is wrong, you have to make it in on line.

**Comment by BlazZupan** [comment]
@ajdapretnar, is this ready to merge?

**Comment by ajdapretnar** [comment]
Yes, it looks fine.

**Pull request merged**
