### PR TITLE
Script for handling documentation from an outer source.

### LINKED ISSUE #21: Widget catalog
Implementation of widgets catalog. Present all widgets and add search function.

### LINKED ISSUE #30: Include external MD content
We need to include external content (e.g. from Orange widget docs) into the current Hugo  project. External MD content will be updated in their original repositories. As symlinking files doesn't work in Hugo (sadly it supports only symlinked folders, not individual files), we need to handle this with CI/CD pipeline.

Proposal:
- external content docs are converted to MD
- we include whole repos in /external folder as git submodules, e.g. external/Orange-widget-foo
- in Hugo content folder we create a file `.hugoinclude`, content format is in `.gitignore` style:

```
external/Orange-widget-foo/docs/  #all files in docs dir
external/Orange-widget-foo/docs/docfile1.md
external/Orange-widget-foo/docs/**/*.md   #recursively include all MD files
```

- we create a script that traverses content folder, reads (optional) `.hugoinclude` files and overwrites in current folder `.hugoinclude`-ed files with content from /external repos (if the file has changed)
- we run this script automatically in CI/CD pipeline (this will ensure that modified/added external content is copied here and rendered

When external repo has changed:
- update submodule
- run script that copies new/modified files
- hugo can now render updated content

We can automate all the steps in CI/CD, and even include hooks that Issues/PRs are automatically created when original content changes.

### PR DESCRIPTION
**Pull request by nejc121**
Script `copy.py` is implemented for handling the copying from an outer source (add-ons documentation). The script uses a file named `widgets_data.json`, which contains `JSON` objects of widgets.  The script copies .md files from a folder named `external` in which submodule is included. In every widget object, there is an attribute called `File`, this attribute tells a script a location of a file that needs to be copy. All widgets documentation files are copied to the location in `content/widget-catalog`.
Widget `JSON` object looks like:
```
"Databases Update": {
    "title": "Databases Update",
    "file": "widgets/databases_update.md",
    "icon": "widgets/icons/databases-update.png",
    "keywords": ["database", "data"],
    "category": "Bioinformatics"
    }

```

`.md` files in documentation should use only  `-` as a separator between words. 

For an update of widget-catalog, you have to use `copy.py` script to copy any new content.

Fixes #30
Fixes #21

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@nejc121 Could you please resolve conflicts, so we I can merge? Thanks!

**Comment by matjazp** [comment]
Are we sure this is the best approach? You need to specifically include one entry for every file we need to copy (no jokers when including files?). Not only that, because metadata for external files is included here, in this repo in .json file, you have to pay attention when modifying external content to also fix data in all other repos where this is used (e.g. when deleting a file, adding a file, etc.).

You can infer all necessary attributes from original .md file with a little planning (e.g. mandatory sections Tags (keywords), icon is the first pic included or is tagged with a comment, etc. This means that new files can be automatically included/deleted/etc in all repos that use the base repo.

**Comment by nejc121** [comment]
@ajdapretnar I resolved the conflicts.

**Comment by ajdapretnar** [comment]
I think we should wait to see if a better solution is possible.

**Comment by ajdapretnar** [comment]
Could @astaric or @markotoplak or someone who knows some web stuff please check and suggest if we should go with the suggestion of @matjazp or is the current implementation ok?

**Comment by ajdapretnar** [comment]
What is the status of this PR?

**Pull request merged**
