### PR TITLE
Few small design and content changes on the home page.

### PR DESCRIPTION
**Pull request by nejc121**
Issues:
- Download button on the home page reloads the page.
- Video links don't open in new tabs.
- Features button in the header doesn't redirect right (half of the first feature is hidden).

Description of changes:

- Download button redirects to the download page.
- Video links are opened in new tab.
- Anchor for features button is fixed and the redirection is working properly now.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Could you please `git rebase -i master` and remove the first two commits from the PR?

**Comment by ajdapretnar** [comment]
Go to Download, then try to click Features. It won't open.

**Comment by ajdapretnar** [comment]
Also all external links should open in a new tab. For example the ones in the footer, YouTube, Twitter, Facebook, StackExchange.

**Comment by nejc121** [comment]
> Also all external links should open in a new tab. For example the ones in the footer, YouTube, Twitter, Facebook, StackExchange.

Fixed #48

**Pull request merged**
